package com.stationery.auth.model;

import jakarta.persistence.*;
import java.time.Instant;

// represents a user in the authentication system, mapped to the "users" table in the database
@Entity 
@Table(name = "users", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class User {
    
    //unique identifier for each user, automatically generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
  
    @Column(nullable = false)
    private String fullName;

    //unique email address of the user, cannot be null
    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false)
    private String password;
    
    // defines role of the user (ADMIN or STUDENT) 
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;
    
    // automatically sets the creation timestamp when a new user is created
    @Column(nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    protected User() { 
    }

// constructor to create a new user with the provided attributes
    public User(String fullName, String email, String password, Role role) {
        this.fullName = fullName;
        this.email = email;
        this.password = password;
        this.role = role;
    }
// they get values of the user attributes
    public Long getId() { return id; }
    public String getFullName() { return fullName; }
    public String getEmail() { return email; }
    public String getPassword() { return password; }
    public Role getRole() { return role; }
    public Instant getCreatedAt() { return createdAt; }
}
